### ISSUE TITLE
CMake build problems for v1.10.x

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#14511]
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Yes.
 
### What version of gRPC and what language are you using?

v1.10.x / C++.   
 
### What operating system (Linux, Windows, …) and version?

Linux, Ubuntu, 16.04

```console
$ uname -a 
Linux ae79522b78cd 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
```console
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
 
### What did you do?

Try to compile the code using cmake:

```console
$ git clone -bv1.10.x https://github.com/grpc/grpc.git grpc-v1.10.x
$ cd grpc-v1.10.x
$ git submodule update --init --recursive
$ sudo docker run -it --rm  --volume $PWD:/v --workdir /v ubuntu:16.04 /bin/bash
# apt update && apt install -y cmake g++ golang
# cmake -H. -B.build -DCMAKE_BUILD_TYPE=Release
...
...
-- Build files have been written to: /v/.build
# cmake --build .build -- -j $(nproc)
...
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

The build fails to complete.

### What did you expect to see?
 
A successful build

### What did you see instead?

The build fails with:

```console
# cmake --build .build -- -j $(nproc)
...
..
/v/third_party/boringssl/ssl/tls_record.cc: In function 'bssl::OpenRecordResult bssl::OpenRecord(SSL*, bssl::Span<unsigned char>*, size_t*, uint8_t*, bssl::Span<unsigned char>)':
/v/third_party/boringssl/ssl/tls_record.cc:595:44: error: 'type' may be used uninitialized in this function [-Werror=maybe-uninitialized]
       if (type != SSL3_RT_APPLICATION_DATA && type != SSL3_RT_ALERT) {
                                            ^
``` 

### Anything else we should know about your project / environment?

Cannot think of anything, but feel free to ask for specifics.

**Comment by mehrdada** [comment]
Just verified the existing `Makefile` without `cmake` works fine (`apt-get install -y build-essential libtool shtool pkg-config automake autoconf; make -j 20').

@jtattermusch any idea why `cmake` fails?

**Comment by mehrdada** [comment]
For the record, simple `cmake . && make -j 30`, which uses Cmake generate Makefiles seems to work as well (I over-installed dependencies as listed above).

**Comment by coryan** [comment]
Thanks for the quick response.  It does not fail on all compilers, not even with all versions of g++.  Here is my build matrix output:

https://travis-ci.org/coryan/google-cloud-cpp/builds/345275128

g++ on Ubuntu 14.04 is fine (that is 4.8 I believe), g++ on Ubuntu 16.04 (5.x I believe), and Ubuntu 17.10 (7.x as I recall) break.

**Comment by coryan** [comment]
Ping.  Any thoughts?

**Comment by jtattermusch** [comment]
@coryan   I think we just need to silence the -Werror=maybe-uninitialized  warning for boringssl compilation.

**Comment by coryan** [comment]
Sure.  Is this something I should expect will happen in v1.10.x or should I wait for v1.11.x?

**Comment by jtattermusch** [comment]
It looks like this warning was already fixed for boringssl: https://boringssl-review.googlesource.com/c/boringssl/+/21724

updating the third_party/boringssl submodule once the fix is available in boringssl's master branch is probably the best way to fix.

**Comment by mehrdada** [comment]
To add, if the resolution is updating the boringssl submodule, we should do it on master and ship it in a later release, not on the 1.10.x branch.

**Comment by coryan** [comment]
Thanks.  I am closing this bug because we know what the resolution will be.

**Comment by amitwaisel** [comment]
@jtattermusch It appears the revision in https://github.com/google/boringssl/blob/4d7ba4e4e57195fcebdabe01489534b446ad02cb/ssl/tls_record.cc#L589 (which is the latest version for v1.10.0) still has the [bug](https://boringssl-review.googlesource.com/c/boringssl/+/21724).
Build still fails on Linux (building Release configuration) using gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
It looks v.1.10.1-pre1 also suffers from the same issue (although master points to a fixed version of boring-ssl).
What is the suggested solution to fix build on Release configuration?

**Comment by mehrdada** [comment]
@amitwaisel This is not surprising as I think the understanding above was not to bump the BoringSSL version on `v1.10.x` branch for a patch release, rather do it on the next major release branch, *i.e.* the `v1.11.x` branch which will be cut from the `master` real soon, which should have a new BoringSSL submodule reference.

**Comment by amitwaisel** [comment]
@mehrdada I completely understand why this is expected, but currently the bottom line is that we can't use the latest version of gRPC because we can't build it in Release with gcc.
So the best solution is either to revert back to `v1.9.x`, or make a local fix before building.

**Comment by jtattermusch** [comment]
I created https://github.com/grpc/grpc/pull/14907 which should fix the build on v1.10.x.

Also, please note that the v1.11.x will be released soon (and it will already contain the fix).
