### ISSUE TITLE
1.12.0 compile error

### ISSUE THREAD

**Issue by AtosNicoS** [grpc/grpc#15534]
### System Information
* Grpc 1.12.0 (For C#)
* OS: ArchLinux x64
* python 3.6.5
* gcc 8.1.0

I compiled with the command line parameter:
```
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 python2 tools/run_tests/run_tests.py -c dbg -l csharp --build_only
```

The errors I get are the following:
```
[C]       Compiling third_party/boringssl/crypto/bio/connect.c
[C]       Compiling third_party/boringssl/crypto/bio/socket_helper.c
[C]       Compiling third_party/boringssl/crypto/bn_extra/bn_asn1.c
mkdir -p `dirname /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/connect.o`
mkdir -p `dirname /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/socket_helper.o`
mkdir -p `dirname /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bn_extra/bn_asn1.o`
cc -pthread -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/address_sorting/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -O0 -fPIC -I. -Iinclude -I/home/user/git/grpc/gens -DPB_FIELD_16BIT -D_DEBUG -DDEBUG -DINSTALL_PREFIX=\"/usr/local\" -DGRPC_TEST_SLOWDOWN_MACHINE_FACTOR=1.000000   -Ithird_party/zlib  -Ithird_party/boringssl/include -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -std=c99 -Wsign-conversion -Wconversion -Wshadow    -Wno-sign-conversion -Wno-conversion -Wno-unused-value -Wno-unknown-pragmas -Wno-implicit-function-declaration -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough  -MMD -MF /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/connect.dep -c -o /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/connect.o third_party/boringssl/crypto/bio/connect.c
cc -pthread -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/address_sorting/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -O0 -fPIC -I. -Iinclude -I/home/user/git/grpc/gens -DPB_FIELD_16BIT -D_DEBUG -DDEBUG -DINSTALL_PREFIX=\"/usr/local\" -DGRPC_TEST_SLOWDOWN_MACHINE_FACTOR=1.000000   -Ithird_party/zlib  -Ithird_party/boringssl/include -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -std=c99 -Wsign-conversion -Wconversion -Wshadow    -Wno-sign-conversion -Wno-conversion -Wno-unused-value -Wno-unknown-pragmas -Wno-implicit-function-declaration -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough  -MMD -MF /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bn_extra/bn_asn1.dep -c -o /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bn_extra/bn_asn1.o third_party/boringssl/crypto/bn_extra/bn_asn1.c
cc -pthread -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/address_sorting/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -O0 -fPIC -I. -Iinclude -I/home/user/git/grpc/gens -DPB_FIELD_16BIT -D_DEBUG -DDEBUG -DINSTALL_PREFIX=\"/usr/local\" -DGRPC_TEST_SLOWDOWN_MACHINE_FACTOR=1.000000   -Ithird_party/zlib  -Ithird_party/boringssl/include -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -std=c99 -Wsign-conversion -Wconversion -Wshadow    -Wno-sign-conversion -Wno-conversion -Wno-unused-value -Wno-unknown-pragmas -Wno-implicit-function-declaration -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough  -MMD -MF /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/socket_helper.dep -c -o /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/socket_helper.o third_party/boringssl/crypto/bio/socket_helper.c
[C]       Compiling third_party/boringssl/crypto/bn_extra/convert.c
mkdir -p `dirname /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bn_extra/convert.o`
third_party/boringssl/crypto/bio/connect.c: In function ‘conn_callback_ctrl’:
third_party/boringssl/crypto/bio/connect.c:491:29: error: cast between incompatible function types from ‘bio_info_cb’ {aka ‘long int (*)(struct bio_st *, int,  const char *, int,  long int,  long int)’} to ‘int (*)(const struct bio_st *, int,  int)’ [-Werror=cast-function-type]
       data->info_callback = (int (*)(const struct bio_st *, int, int))fp;
                             ^
cc -pthread -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/address_sorting/include -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -O0 -fPIC -I. -Iinclude -I/home/user/git/grpc/gens -DPB_FIELD_16BIT -D_DEBUG -DDEBUG -DINSTALL_PREFIX=\"/usr/local\" -DGRPC_TEST_SLOWDOWN_MACHINE_FACTOR=1.000000   -Ithird_party/zlib  -Ithird_party/boringssl/include -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -std=c99 -Wsign-conversion -Wconversion -Wshadow    -Wno-sign-conversion -Wno-conversion -Wno-unused-value -Wno-unknown-pragmas -Wno-implicit-function-declaration -Wno-unused-variable -Wno-sign-compare -Wno-implicit-fallthrough  -MMD -MF /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bn_extra/convert.dep -c -o /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bn_extra/convert.o third_party/boringssl/crypto/bn_extra/convert.c
cc1: all warnings being treated as errors
make: *** [Makefile:2804: /home/user/git/grpc/objs/dbg/third_party/boringssl/crypto/bio/connect.o] Error 1
make: *** Waiting for unfinished jobs....
src/core/lib/surface/channel.cc: In function ‘grpc_channel* grpc_channel_create_with_builder(grpc_channel_stack_builder*, grpc_channel_stack_type)’:
src/core/lib/surface/channel.cc:106:38: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘grpc_channel’ {aka ‘struct grpc_channel’} with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(channel, 0, sizeof(*channel));
                                      ^
src/core/lib/surface/channel.cc:60:8: note: ‘grpc_channel’ {aka ‘struct grpc_channel’} declared here
 struct grpc_channel {
        ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:2819: /home/user/git/grpc/objs/dbg/src/core/lib/surface/channel.o] Error 1
FAILED: make [ret=2, pid=7487, time=1.4sec]
FAILED: Some tests failed
```

I could "solve"/ignore the memset error by commenting out the line. I am extremely unsure if that does not cause errors. I was unable to solve the boringssl error yet.

**Comment by apolcyn** [comment]
This is a dupe of #15520, but I'll leave this open just since it's hitting a different compiler error.

Overall looks like it's running into <i>one</i> of the different errors compiler errors you get when trying use gcc-8, but it falls under the general category of grpc not compiling under gcc-8, which is addressed by https://github.com/grpc/grpc/pull/15532.

**Comment by AtosNicoS** [comment]
As a temporary workaround I installed `gcc7` for ArchLinux and used the following line to compile grpc 1.12.1:
```
CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 python2 tools/run_tests/run_tests.py -c dbg -l csharp --build_only
```

**Comment by DevJohnC** [comment]
A year later and this is still an issue, perhaps the BUILDING.md document should be updated to specify the use of GCC/G++ 7 on linux.

**Comment by sampointer** [comment]
Should anybody else be trying to build this and hit the same errors the following `Dockerfile` creates a buildable container image that can be used similarly to a local binary: `docker run --network=host grpc_cli ls localhost:9090`

```Dockerfile
# Build with `docker build . -t grpc_cli:latest`
FROM golang:latest AS build
RUN apt-get update
RUN apt-get install build-essential autoconf libtool pkg-config libgflags-dev -y
WORKDIR src
RUN mkdir github.com
WORKDIR github.com
RUN git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
WORKDIR grpc
RUN git submodule update --init
# https://github.com/grpc/grpc/issues/15534
RUN apt-get install gcc-7 g++-7 -y
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 50
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 50
RUN make grpc_cli
ENTRYPOINT [ "/go/src/github.com/grpc/bins/opt/grpc_cli" ]
```

**Comment by labkode** [comment]
Still an issue with latest stable version, @sampointer instructions should be promoted to the official dependencies to be installed.

**Comment by jtattermusch** [comment]
@apolcyn  where are we with fixing the gcc 8.1 build?

**Comment by jtattermusch** [comment]
I'm going to close this as it seems to be basically about gcc8.1 support and accoding to https://github.com/grpc/grpc/issues/16675, that's already fixed (you should use a newer version than gRPC C# 1.12 though)
