### ISSUE TITLE
grpc_basictests_objc_dbg: failing consistently on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17814]
Last 3 builds have failed:
https://source.cloud.google.com/results/invocations/9cb769ad-5fd2-4105-8668-b22520239e14/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/2895a303-3938-43cd-b299-333e3bd2605a/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/df9af48f-319d-4995-a3c0-76440c681bcf/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests

It's complaining that random files are missing:
```
Write auxiliary files
/bin/mkdir -p /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/route_guide/Build/Build/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64
write-file /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/route_guide/Build/Build/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/arm64/gRPC-Core.LinkFileList
/bin/mkdir -p /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/route_guide/Build/Build/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/armv7
write-file /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/route_guide/Build/Build/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/gRPC-Core.build/Objects-normal/armv7/gRPC-Core.LinkFileList
clang: error: no such file or directory: '/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/route_guide/Pods/gRPC-Core/src/core/lib/iomgr/resolve_address_windows.cc'
clang: error: no input files
```

**Comment by muxi** [comment]
I'll hold off #17816 since the builds seems to be green again; probably a Kokoro regression. Will continue keep an eye on it though.

**Comment by jtattermusch** [comment]
Last 5 runs have failed again:
https://source.cloud.google.com/results/invocations/1e891c3e-76be-476d-9e70-0f15670ea980/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/5ee2a127-f3cc-43fc-8316-3b7633d76c37/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/231b7225-f4d2-4bd9-9d80-5bac58b6c55e/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests

There might be multiple problems:

- cfstream is failing with segfault
- seeing the "file not found" and "no such file or directory" problem again (and there has to be a logical explanation)

**Comment by muxi** [comment]
CFStream failure is identified and also fixed in #17816.

**Comment by jtattermusch** [comment]
This has been failing consistently for the past 12 days.

**Comment by muxi** [comment]
Thanks for the notice. Making changes in process.

**Comment by jtattermusch** [comment]
It seems that https://github.com/grpc/grpc/pull/17948 has improved the runtime of the suite,
but unfortunately the testsuite is still failing (possibly with a different error now):

https://source.cloud.google.com/results/invocations/6b32db56-a7da-4778-8726-4639e4b962e6/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/0b63de0b-0a87-4fad-a895-93c8e1f54667/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests

e.g
```
2019-02-11 22:51:29.476800-0800 xctest[95446:157032] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to report test assertion failure '((challengeHeader.length) greater than (0)) failed: throwing "Unable to report test assertion failure '((challengeHeader.length) greater than (0)) failed: ("0") is not greater than ("0") - No challenge in response headers {
}' from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/src/objective-c/tests/GRPCClientTests.m:622 because it was raised inside test case -[GRPCClientTests testErrorDebugInformation] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished." - No challenge in response headers {
}' from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/src/objective-c/tests/GRPCClientTests.m:622 because it was raised inside test case -[GRPCClientTests testErrorDebugInformation] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ff7829b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f514735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ff78022 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010edd7c10 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   XCTest                              0x000000010f3e778f -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:] + 1034
	5   XCTest                              0x000000010f3f0f6c _XCTFailureHandler + 408
	6   AllTests                            0x000000012734aab0 __44-[GRPCClientTests testErrorDebugInformation]_block_invoke.409 + 6608
	7   AllTests                            0x000000012750f3ea __42-[GRXConcurrentWriteable cancelWithError:]_block_invoke + 86
	8   libdispatch.dylib                   0x00000001120cf51d _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00000001120d0587 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00000001120dc3bc _dispatch_main_queue_callback_4CF + 1290
	11  CoreFoundation                      0x000000010fedb7f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x000000010fed5e86 __CFRunLoopRun + 2342
	13  CoreFoundation                      0x000000010fed5221 CFRunLoopRunSpecific + 625
	14  XCTest                              0x000000010f42a4ad -[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 545
	15  XCTest                              0x000000010f3db4d5 -[XCTestCase(AsynchronousTesting) _waitForExpectations:timeout:enforceOrder:handler:] + 132
	16  XCTest                              0x000000010f3db67a -[XCTestCase(AsynchronousTesting) waitForExpectationsWithTimeout:handler:] + 287
	17  AllTests                            0x0000000127334ea5 -[GRPCClientTests testMetadata] + 997
	18  CoreFoundation                      0x000000010ff7f11c __invoking___ + 140
	19  CoreFoundation                      0x000000010ff7c5b5 -[NSInvocation invoke] + 325
	20  XCTest                              0x000000010f3e7e30 __24-[XCTestCase invokeTest]_block_invoke + 591
	21  XCTest                              0x000000010f43117e -[XCUITestContext performInScope:] + 183
	22  XCTest                              0x000000010f3e7bd6 -[XCTestCase invokeTest] + 141
	23  XCTest                              0x000000010f3e8b97 __26-[XCTestCase performTest:]_block_invoke.369 + 42
	24  XCTest                              0x000000010f435f25 +[XCTContext runInContextForTestCase:block:] + 163
	25  XCTest                              0x000000010f3e8533 -[XCTestCase performTest:] + 608
	26  XCTest                              0x000000010f3e4539 __27-[XCTestSuite performTest:]_block_invoke + 363
	27  XCTest                              0x000000010f3e3ea0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	28  XCTest                              0x000000010f3e409d -[XCTestSuite performTest:] + 239
	29  XCTest                              0x000000010f3e4539 __27-[XCTestSuite performTest:]_block_invoke + 363
	30  XCTest                              0x000000010f3e3ea0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	31  XCTest                              0x000000010f3e409d -[XCTestSuite performTest:] + 239
	32  XCTest                              0x000000010f3e4539 __27-[XCTestSuite performTest:]_block_invoke + 363
	33  XCTest                              0x000000010f3e3ea0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	34  XCTest                              0x000000010f3e409d -[XCTestSuite performTest:] + 239
	35  XCTest                              0x000000010f43d64f __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	36  XCTest                              0x000000010f3f771a -[XCTestObservationCenter _observeTestExecutionForBlock:] + 475
	37  XCTest                              0x000000010f43d4ee -[XCTTestRunSession runTestsAndReturnError:] + 281
	38  XCTest                              0x000000010f3d3af1 -[XCTestDriver runTestsAndReturnError:] + 314
	39  XCTest                              0x000000010f435190 _XCTestMain + 619
	40  xctest                              0x000000010eab0591 xctest + 9617
	41  libdyld.dylib                       0x0000000112140551 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

btw, please note that the interop test backends are currently down (not sure if ObjC tests depend on them).

**Comment by muxi** [comment]
I think that is exactly the reason. Local tests seem to be ok; interop tests with `grpc-test.sandbox.googleapis.com` are failing.

**Comment by muxi** [comment]
Oh and just checked the test status again. The most recent two master builds passed, probably because the interop test backends have been fixed.
