### ISSUE TITLE
gRPC server becomes unresponsive

### ISSUE THREAD

**Issue by jaaant** [grpc/grpc#18848]
### What version of gRPC and what language are you using?
 gRPC 1.17.1, C++
 
### What operating system (Linux, Windows,...) and version?
 Windows 10 Enterprise, build 1809
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2017, version 15.6.2
 
### What did you do?
We're in the process of taking gRPC into use, and have synchronous calls working for the most part. Recently we implemented preliminary code for handling asynchronous calls: we added a completion queue to ServerBuilder and created a thread to get tasks from it. We don't yet have any asynchronous services registered.
 
### What did you expect to see?
 Synchronous services keep working as before.
 
### What did you see instead?
 Synchronous services work at first, but at some point, typically within a timeframe of tens of minutes to a few hours, the gRPC server becomes unresponsive. Neither existing nor new channels work, and the only solution is to restart the server.

Based on our logs and gRPC trace, once the error occurs new channels can still be created seemingly successfully. However, calls made through those channels never get a response. The client either times out or waits forever if no deadline has been set.

The following is a snippet from a client-side trace log as the failing call begins, with GRPC_TRACE=all and GRPC_VERBOSITY=debug, filtered through our logging system.

```
2019-04-18T06:23:15.239Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\ext\transport\chttp2\transport\stream_lists.cc, 125: 000001F63371CE30[1][cli]: add to writing
2019-04-18T06:23:15.239Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\ext\transport\chttp2\transport\stream_lists.cc, 71: 000001F63371CE30[1][cli]: pop from writing
2019-04-18T06:23:15.246Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 000001F63371E820: SET 3579 now 3479 call 000001F63371E668[00007FF7A09091A0]
2019-04-18T06:23:15.247Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 17 with queue_deadline_cap=4177 => is_first_timer=true
2019-04-18T06:23:15.247Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 423:   .. old shard min_deadline=4178
2019-04-18T06:23:15.347Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 549: TIMER 000001F63371E820: FIRE 0ms late via combiner:immediately scheduler
2019-04-18T06:23:16.943Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 549: TIMER 000001F62EC72380: FIRE 0ms late via exec_ctx scheduler
2019-04-18T06:23:16.943Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 000001F62EC72380: SET 10175 now 5175 call 000001F62EC723B8[00007FF7A0911B10]
2019-04-18T06:23:16.943Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 21 with queue_deadline_cap=5180 => is_first_timer=false
2019-04-18T06:23:21.943Z t000016f8  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 549: TIMER 000001F62EC72380: FIRE 0ms late via exec_ctx scheduler
2019-04-18T06:23:21.943Z t000016f8  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 000001F62EC72380: SET 15175 now 10175 call 000001F62EC723B8[00007FF7A0911B10]
2019-04-18T06:23:21.943Z t000016f8  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 21 with queue_deadline_cap=10185 => is_first_timer=false
2019-04-18T06:23:23.641Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 549: TIMER 000001F63371E998: FIRE 0ms late via combiner:immediately scheduler
2019-04-18T06:23:23.641Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 000001F63371E9D0: SET 16873 now 11873 call 000001F63371E948[00007FF7A0909910]
2019-04-18T06:23:23.641Z t00004428  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 14 with queue_deadline_cap=12183 => is_first_timer=false
2019-04-18T06:23:23.675Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 000001F63371E820: SET 12107 now 11907 call 000001F63371E668[00007FF7A09091A0]
2019-04-18T06:23:23.676Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 17 with queue_deadline_cap=12267 => is_first_timer=true
2019-04-18T06:23:23.676Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 423:   .. old shard min_deadline=12268
2019-04-18T06:23:23.676Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 467: TIMER 000001F63371E9D0: CANCEL pending=true
2019-04-18T06:23:23.677Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 000001F63371E998: SET 21907 now 11907 call 000001F63371E858[00007FF7A0909500]
2019-04-18T06:23:23.677Z t00003dac  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 10 with queue_deadline_cap=12187 => is_first_timer=false
2019-04-18T06:23:23.875Z t000016f8  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 549: TIMER 000001F63371E820: FIRE 0ms late via combiner:immediately scheduler
```

After that, similar timer messages keep repeating every few seconds. For comparison, a successful call at client-side looks like this:

```
2019-04-18T12:16:23.108Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\ext\transport\chttp2\transport\stream_lists.cc, 125: 0000022FA4CC8760[1][cli]: add to writing
2019-04-18T12:16:23.108Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\ext\transport\chttp2\transport\stream_lists.cc, 71: 0000022FA4CC8760[1][cli]: pop from writing
2019-04-18T12:16:23.109Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 0000022FA4CCA150: SET 1857 now 1757 call 0000022FA4CC9F98[00007FF7502591A0]
2019-04-18T12:16:23.109Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 23 with queue_deadline_cap=2116 => is_first_timer=true
2019-04-18T12:16:23.109Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 423:   .. old shard min_deadline=2117
2019-04-18T12:16:23.208Z t00007170  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 549: TIMER 0000022FA4CCA150: FIRE 0ms late via combiner:immediately scheduler
2019-04-18T12:16:23.467Z t00003e54  <gRPC-core> DEBUG I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\surface\call.cc, 719: set_final_status CLI
2019-04-18T12:16:23.468Z t00003e54  <gRPC-core> DEBUG I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\surface\call.cc, 720: "No Error"
2019-04-18T12:16:23.468Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\surface\completion_queue.cc, 782: cq_end_op_for_pluck(cq=0000022FA4CAC6F0, tag=0000007D1F8F7EA0, error="No Error", done=00007FF7501ECC60, done_arg=0000022FA4CCB450, storage=0000022FA4CCB4C8)
2019-04-18T12:16:23.468Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 467: TIMER 0000022FA4CCA2C8: CANCEL pending=true
2019-04-18T12:16:23.469Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 365: TIMER 0000022FA4CCA2C8: SET 12116 now 2116 call 0000022FA4CCA188[00007FF750259500]
2019-04-18T12:16:23.469Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\iomgr\timer_generic.cc, 401:   .. add to shard 15 with queue_deadline_cap=3117 => is_first_timer=false
2019-04-18T12:16:23.469Z t00003e54  <gRPC-core> INFO  I:\git\vcpkg\buildtrees\grpc\src\v1.17.1-3c2b344641\src\core\lib\surface\completion_queue.cc, 1299: RETURN_EVENT[0000022FA4CAC6F0]: OP_COMPLETE: tag:0000007D1F8F7EA0 OK
```

The server-side logs don't show anything obviously erroneous. They don't have all tracers on, though. Interestingly, when we ran the server with all tracers on in an environment where failures were previously common, no failure occurred. If that's not just a fluke, it might hint at a race condition where the delay caused by logging changes the result.

Full logs are attached (with some information redacted). [failure_server.txt](https://github.com/grpc/grpc/files/3111862/failure_server.txt) shows logs from a server that eventually became unresponsive. [failure_client.txt](https://github.com/grpc/grpc/files/3111866/failure_client.txt) shows a test call made to the server after that. [success_server.txt](https://github.com/grpc/grpc/files/3111867/success_server.txt) and [success_client.txt](https://github.com/grpc/grpc/files/3111868/success_client.txt) show a successful call to server; the former ends abruptly because the server was run and terminated from a debugger.
 
### Anything else we should know about your project / environment?
Our server application is actually running two gRPC servers side by side. As far as we can tell, they both break down at the same time.

The problem also depends on the environment: it occurs regularly on some computers and not at all on others. We have yet to isolate the relevant factor in this.

**Comment by AspirinSJL** [comment]
Sorry for late response. I suggest trying newer version to see if this still exists.

**Comment by Rantanen** [comment]
On it. Took a while to build the reproduction setup.

I've just done a sanity check to verify that my setup still reproduces this with 1.21.

I'm currently compiling 1.24.2 to check that one. If the issue still exists there, I should be able to also verify #20376. I'll try to report back tomorrow.

**Comment by AspirinSJL** [comment]
Thanks!

**Comment by Rantanen** [comment]
The build was fast enough that I got it tested before heading off.

This still reproduces on 1.24.2. I did make one change to the code base by adding the `created` flag to the thread constructor in thread_manager.cc:

```c++
  bool created = false;  // Added
  thd_ = grpc_core::Thread(
      "grpcpp_sync_server",
      [](void* th) { static_cast<ThreadManager::WorkerThread*>(th)->Run(); },
      this, &created);  // Added &created
  if (!created) abort();  // Added
```

If I understood #20376 correctly, then that `abort()` should have triggered if the issue would be fixed by #20376. The server froze in the "won't accept new requests" -state without aborting.

**Comment by jtattermusch** [comment]
Should be fixed by https://github.com/grpc/grpc/pull/19311 - getting a confirmation would be good.

**Comment by Rantanen** [comment]
I work with @jaaant and we've had #19311 applied to our gRPC builds for few months now - although if I remember correctly, our builds are based on gRPC 1.18.x since having to patch things manually for the vcpkg is annoying. We'll try to upgrade to v1.26.0 (without any patches) once that releases and we'll let you know if we still have the issue. For now I'm assuming this issue is resolved.
