### ISSUE TITLE
Cannot install GRPC - exit status 1

### ISSUE THREAD

**Issue by MikeK-10** [grpc/grpc#20879]
### What version of gRPC and what language are you using?
no GRPC as yet :( 
Python 3.8 
PIP 19.3.1

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```
python -m pip install grpcio
Collecting grpcio
  Using cached https://files.pythonhosted.org/packages/4c/0e/2c93f6f21ef63696d0b3d65bd7dddf5fd5aafc5219cee49e669be3878f6b/grpcio-1.24.3.tar.gz
Requirement already satisfied: six>=1.5.2 in c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages (from grpcio) (1.12.0)
Installing collected packages: grpcio
    Running setup.py install for grpcio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-dge12g7k\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-dge12g7k\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-fiti458l\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\username\AppData\Local\Temp\pip-install-dge12g7k\grpcio\
    Complete output (62 lines):
    Found cython-generated files...
    running install
    running build
    running build_py
    running build_project_metadata
    creating python_build
    creating python_build\lib.win32-3.8
    creating python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_common.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_server.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win32-3.8\grpc
    copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win32-3.8\grpc
    creating python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win32-3.8\grpc\beta
    copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win32-3.8\grpc\beta
    creating python_build\lib.win32-3.8\grpc\experimental
    copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win32-3.8\grpc\experimental
    copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win32-3.8\grpc\experimental
    copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win32-3.8\grpc\experimental
    creating python_build\lib.win32-3.8\grpc\framework
    copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win32-3.8\grpc\framework
    creating python_build\lib.win32-3.8\grpc\_cython
    copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win32-3.8\grpc\_cython
    creating python_build\lib.win32-3.8\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win32-3.8\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win32-3.8\grpc\framework\common
    copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win32-3.8\grpc\framework\common
    creating python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win32-3.8\grpc\framework\foundation
    creating python_build\lib.win32-3.8\grpc\framework\interfaces
    copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win32-3.8\grpc\framework\interfaces
    creating python_build\lib.win32-3.8\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\base
    copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\base
    creating python_build\lib.win32-3.8\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\face
    copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\face
    creating python_build\lib.win32-3.8\grpc\_cython\_cygrpc
    copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win32-3.8\grpc\_cython\_cygrpc
    creating python_build\lib.win32-3.8\grpc\_cython\_credentials
    copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win32-3.8\grpc\_cython\_credentials
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\username\AppData\Local\Programs\Python\Python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-dge12g7k\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-dge12g7k\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-fiti458l\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

### What did you expect to see?
Successful install

### What did you see instead?
The error above

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment]
I'm able to reproduce on 1.19.0+. The problem appears in all from-source builds, which Python 3.8 just happens to be until https://github.com/grpc/grpc/issues/20615 is resolved.

**Comment by gnossen** [comment]
Downgrading to P3 since this only affects from-source Windows builds, which should be a tiny minority of users.

Since we're able to generate binaries from the git repo as part of CI, the Windows build process clearly works. The problem is either:
 - Some dependency is missing on default Windows installs
 - Some file is being left out of the `.tar.gz` source builds we're packaging

If anyone would like to help investigate this, it would be appreciated.

**Comment by gnossen** [comment]
@MikeK-10 For the moment, switching to Python 3.7 should be a good option for you. We should have Python 3.8 binaries publishing in the near future.

**Comment by barcharcraz** [comment]
that particular error appears to come from "commands.py" testing if the compiler is OK with mutliple -std options by running "cc"

"cc" is not going to be the correct compiler on windows (and actually it's not the correct compiler in ANY situation where you're not using the "system" compiler or where cc is not a symlink)

Even after removing that though things still won't compile on windows, due to missing zlib headers

I get the feeling the CI packages are generated using a separate buildsystem (maybe bezel....) would it be possible to provide documentation on how that build works?

**Comment by gnossen** [comment]
No, the Windows [build uses `setup.py`](https://github.com/grpc/grpc/blob/master/tools/run_tests/artifacts/build_artifact_python.bat). It seems there's just some difference in state/configuration between our CI build and a default Windows set-up. You can invoke that build with `task_runner.py` [like so](https://github.com/grpc/grpc/blob/master/tools/internal_ci/windows/grpc_build_artifacts.bat#L31).

The point about the compiler certainly is a good one. I seem to remember there was an external contribution about that pending, but I can't seem to find it now.

**Comment by barcharcraz** [comment]
I got it working on windows after changing the cc thing and also remembering to checkout the submodules btw.

**Comment by leonbloy** [comment]
Also happening with 1.25  (Windows 7, 64 bits, Python 3.8)

BTW: I guess the message `Check the logs for full command output.`
refers to `C:\Users\h\AppData\Local\Temp\pip-record-sqsciy62\install-record.txt` ?
If so, the parent directory seems to be deleted by the (failed) installation script... kinda ironic, at least, no?

```
c:\dev\Python38>py -m pip  install grpcio
Collecting grpcio
  Using cached https://files.pythonhosted.org/packages/e4/60/40c4d2b61d9e4349bc89445deb8d04cc000b10a63446c42d311e0d21d127/grpcio-1.25.0.tar.gz
Requirement already satisfied: six>=1.5.2 in c:\users\h\appdata\roaming\python\python38\site-packages (from grpcio) (1.12.0)
Installing collected packages: grpcio
    Running setup.py install for grpcio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\dev\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\h\\AppData\\Local\\Temp\\pip-install-o4wgah9h\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\h\\AppData\\Local\\Temp\\pip-install-o4wgah9h\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\h\AppData\Local\Temp\pip-record-sqsciy62\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\h\AppData\Local\Temp\pip-install-o4wgah9h\grpcio\
    Complete output (66 lines):
       ...
    creating python_build\lib.win32-3.8\grpc\_cython\_credentials
    copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win32-3.8\grpc\_cython\_credentials
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\dev\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\h\\AppData\\Local\\Temp\\pip-install-o4wgah9h\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\h\\AppData\\Local\\Temp\\pip-install-o4wgah9h\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install--record 'C:\Users\h\AppData\Local\Temp\pip-record-sqsciy62\install-record.txt'--single-version-externally-managed --compile Check the logs for full command output.

```

**Comment by gnossen** [comment]
https://github.com/grpc/grpc/pull/20386 was the PR I referred to earlier in the thread.
