### ISSUE TITLE
Tests that load "main" from a shared library don't work on ARM64 (under bazel)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#25288]
Tests known to be impacted:
- fuzzer tests (that import "main" from fuzzer_corpus_test.cc). https://github.com/grpc/grpc/blob/73978ad0471832932517876da9d38a14b8f1d9a6/test/core/util/fuzzer_corpus_test.cc#L157
- `//test/cpp/end2end:end2end_test` (where main is in the end2end_test_lib)

Problem:
- When the test binary starts,  _start function is first invoked and it invokes [__libc_start_main](https://refspecs.linuxbase.org/LSB_3.1.0/LSB-generic/LSB-generic/baselib---libc-start-main-.html) with the address of main as the first parameter.
- since the main function is in a shared library, the test binary has an undefined symbol for main (=null), which gets resolved when the shared library is loaded.
- On x86_64, the address of main is resolved correctly, the right address of main is passed to __libc_start_main and the binary works just fine.
- On ARM64, the address is not resolved correctly and 0 is passed as main's address (it never gets resolved) That leads to crash.

x86_64 dissasembly of the _start entry point
```
00000000004033a0 <_start>:
  4033a0:       31 ed                   xor    %ebp,%ebp
  4033a2:       49 89 d1                mov    %rdx,%r9
  4033a5:       5e                      pop    %rsi
  4033a6:       48 89 e2                mov    %rsp,%rdx
  4033a9:       48 83 e4 f0             and    $0xfffffffffffffff0,%rsp
  4033ad:       50                      push   %rax
  4033ae:       54                      push   %rsp
  4033af:       4c 8d 05 1a 44 02 00    lea    0x2441a(%rip),%r8        # 4277d0 <__libc_csu_fini>
  4033b6:       48 8d 0d b3 43 02 00    lea    0x243b3(%rip),%rcx        # 427770 <__libc_csu_init>
  4033bd:       48 8b 3d 3c da 02 00    mov    0x2da3c(%rip),%rdi        # 430e00 <main>

^ this is where address of "main" is set to be passed to __libc_start_main

  4033c4:       ff 15 3e da 02 00       callq  *0x2da3e(%rip)        # 430e08 <__libc_start_main@GLIBC_2.2.5>
  4033ca:       f4                      hlt    
  4033cb:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)
```

ARM64 disassembly of the _start entry point, 
```
0000000000403190 <_start>:
  403190:       d280001d        mov     x29, #0x0                       // #0
  403194:       d280001e        mov     x30, #0x0                       // #0
  403198:       aa0003e5        mov     x5, x0
  40319c:       f94003e1        ldr     x1, [sp]
  4031a0:       910023e2        add     x2, sp, #0x8
  4031a4:       910003e6        mov     x6, sp
  4031a8:       d2e00000        movz    x0, #0x0, lsl #48
  4031ac:       f2c00000        movk    x0, #0x0, lsl #32
  4031b0:       f2a00000        movk    x0, #0x0, lsl #16
  4031b4:       f2800000        movk    x0, #0x0

^ PROBLEM HERE
   HERE is where address of "main" is supposed to be set (first arg of __libc_start_main). But x0 register is
   actually being set to 0.

  4031b8:       d2e00003        movz    x3, #0x0, lsl #48
  4031bc:       f2c00003        movk    x3, #0x0, lsl #32
  4031c0:       f2a00843        movk    x3, #0x42, lsl #16
  4031c4:       f29e8d03        movk    x3, #0xf468
  4031c8:       d2e00004        movz    x4, #0x0, lsl #48
  4031cc:       f2c00004        movk    x4, #0x0, lsl #32
  4031d0:       f2a00844        movk    x4, #0x42, lsl #16
  4031d4:       f29e9d04        movk    x4, #0xf4e8
  4031d8:       97ffff12        bl      402e20 <__libc_start_main@plt>
  4031dc:       97ffff15        bl      402e30 <abort@plt>
```

This problem only exhibits if the "main" function is not in the binary itself, but in a shared library (otherwise everything works alright).

Reproduction:
on ARM machine run `tools/bazel test --config=dbg //test/core/slice:b64_encode_fuzzer`. It will segfault with said problem.

It still haven't figured out if this is a bazel problem or if it's related to a general limitation on linux aarch64.

**Comment by jtattermusch** [comment]
@nicolasnoble  @gnossen  @veblush  feel free to chime in - this is the issue I mentioned in our syncup. It's quite interesting IMHO.

Btw the problem can be worked around by using `--dynamic_mode=off` bazel flag to force the library with main to be linked statically but doing that in turn breaks other tests.

**Comment by gnossen** [comment]
Not an ARM expert, but I find two things odd.

1. I'd expect an address within the global offset table, not `0x0`.
2. Why did the compiler generate four instructions to move a quadword 0 to the register instead of a single `mov x1, #0x0`? It usually does this when moving a single word, right?

I tried to reproduce myself, but I don't have access to an aarch64 machine and it's much harder than expected to build Bazel on a 32 bit ARM machine.

@jtattermusch Can you attach the full output of `objdump -D`?

**Comment by jtattermusch** [comment]
@gnossen  full `objdump -D` (for b64_encode_fuzzer binary) is here:
https://paste.c-net.org/SmokeySprayed

**Comment by resistor** [comment]
> 2. Why did the compiler generate four instructions to move a quadword 0 to the register instead of a single `mov x1, #0x0`? It usually does this when moving a single word, right?

The address is supposed to get resolved by either the static or dynamic linker - the compiler doesn't know the address of main at compile time. Materializing an arbitrary constant takes four instructions in AArch64, so the compiler inserts the four instructions but leaves the immediate value empty. The linker is supposed to patch the immediate values to contain the proper address.

@jtattermusch Is the disassembly you posted static or at runtime?

**Comment by resistor** [comment]
@jtattermusch Also, can you confirm what environment you're seeing this in? I'm looking at the relevant CRT files in the environments I know about, and it doesn't match what's in your binary.

**Comment by jtattermusch** [comment]
> > 1. Why did the compiler generate four instructions to move a quadword 0 to the register instead of a single `mov x1, #0x0`? It usually does this when moving a single word, right?
> 
> The address is supposed to get resolved by either the static or dynamic linker - the compiler doesn't know the address of main at compile time. Materializing an arbitrary constant takes four instructions in AArch64, so the compiler inserts the four instructions but leaves the immediate value empty. The linker is supposed to patch the immediate values to contain the proper address.
> 
> @jtattermusch Is the disassembly you posted static or at runtime?

It's a static disassembly of the binaries as built by bazel.

**Comment by jtattermusch** [comment]
> @jtattermusch Also, can you confirm what environment you're seeing this in? I'm looking at the relevant CRT files in the environments I know about, and it doesn't match what's in your binary.

It's ubuntu 18.04.5 LTS aarch64 (and it's actually a AWS EC2 Graviton2 VM)

**Comment by jtattermusch** [comment]
I also tested the bazel build with clang-10 and got the same error as originally reported (still cannot load "main")

**Comment by jtattermusch** [comment]
Interestingly, when I tried the same repro command, but forced using gcc/g++, the problem went away (and I'm now able to run the binary just fine and the "main" function gets called correctly.

`CC=gcc CXX=g++ tools/bazel test --config=dbg //test/core/slice:b64_encode_fuzzer`


objdump -D   of the _start entry point (after built with GCC)
```
0000000000003990 <_start>:
    3990:       d280001d        mov     x29, #0x0                       // #0
    3994:       d280001e        mov     x30, #0x0                       // #0
    3998:       aa0003e5        mov     x5, x0
    399c:       f94003e1        ldr     x1, [sp]
    39a0:       910023e2        add     x2, sp, #0x8
    39a4:       910003e6        mov     x6, sp
    39a8:       900001e0        adrp    x0, 3f000 <__FRAME_END__+0x12bf0>
    39ac:       f946b000        ldr     x0, [x0, #3424]
    39b0:       900001e3        adrp    x3, 3f000 <__FRAME_END__+0x12bf0>
    39b4:       f946b463        ldr     x3, [x3, #3432]
    39b8:       900001e4        adrp    x4, 3f000 <__FRAME_END__+0x12bf0>
    39bc:       f946b884        ldr     x4, [x4, #3440]
    39c0:       97ffff14        bl      3610 <__libc_start_main@plt>
    39c4:       97ffff17        bl      3620 <abort@plt>
```

my gcc version:
```
gcc --version
gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
```

So it looks like this is either a clang bug (I find that hard to believe) or it still could be bazel issue?

**Comment by resistor** [comment]
I actually think it's likely to be a linker bug, or a mismatch between your libc's expectations and your linker's. Can you tell if clang is using lld on your system?

**Comment by resistor** [comment]
I guess a clang bug isn't out of the question either - clang 6.0 is from March 2018.

**Comment by jtattermusch** [comment]
> I guess a clang bug isn't out of the question either - clang 6.0 is from March 2018.

I was able to reproduce the same behavior with clang 10 as well.

**Comment by jtattermusch** [comment]
> I actually think it's likely to be a linker bug, or a mismatch between your libc's expectations and your linker's. Can you tell if clang is using lld on your system?

I ran a few tests with interesting findings:

- `tools/bazel test --config=opt //test/core/slice:b64_encode_fuzzer`  (uses clang and  gold linker via `-fuse-ld=/usr/bin/ld.gold`):     FAILS
- `CC=gcc CXX=g++ tools/bazel test --config=opt //test/core/slice:b64_encode_fuzzer`  (uses gold linker via `-fuse-ld=gold`):  PASSES
- `tools/bazel test --config=opt --linkopt="-fuse-ld=/usr/bin/ld.lld-10" //test/core/slice:b64_encode_fuzzer`: PASSES

so the clang + gold combination fails, and using clang with lld-10 makes the test pass.
But when compiled with gcc, it  works even with gold linker. 
So we still cannot clearly says whether it's the compiler that's at fault of  its the linker.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/25517 has been merged as a workaround.

**Comment by jtattermusch** [comment]
We still don't know the original rootcause, but the workaround seems to be working reliably. Closing since currently this issue is not actionable.
