### ISSUE TITLE
grpc_absl_log Introduces Segmentation Fault in 1.68.0 for PHP 8.3 on Debian Bookworm

### ISSUE THREAD

**Issue by jakeschroeder-fountaindigital** [grpc/grpc#38184]
### What version of gRPC and what language are you using?
gRPC via pecl 1.68.0
PHP 8.3

### What operating system (Linux, Windows,...) and version?
Debian Bookworm

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Perform any operation with the gRPC transport in Google Ads PHP SDK 25.0.0
I.e., GoogleAdsServiceClient::search()

### What did you expect to see?
PagedListResponse

### What did you see instead?
[Error: ](error: Maximum call stack size of 8339456 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
Originates from UnaryCall->Call->submitBatch()

### Anything else we should know about your project / environment?
Built by Docker. Works with grpc 1.66. Google Ads PHP SDK works with transport = 'rest'.

Diff in php/ext from 1.66 to 1.68 was the logging function change.

**Comment by romanstingler** [comment]
probably also https://github.com/googleapis/gax-php/issues/581
@stanley-cheung

**Comment by stanley-cheung** [comment]
Has this been fixed with a newer version of the grpc extension? I remember seeing a few fixes related to this in the last few releases.

**Comment by haizadvnet** [comment]
> Has this been fixed with a newer version of the grpc extension? I remember seeing a few fixes related to this in the last few releases.

The latest version on [PECL](https://pecl.php.net/package-changelog.php?package=gRPC) is 1.70.0, but it's unclear if [v1.70.1](https://github.com/grpc/grpc/releases/tag/v1.70.1) addresses this.

I am using grpc 1.70.0, and still get similar error:`Uncaught Error: Maximum call stack size of 10436608 bytes (zend.max_allowed_stack_size -
zend.reserved_stack_size) reached. Infinite recursion?`

PHP Version 8.3.10

**Comment by Cristobal-M** [comment]
> > Has this been fixed with a newer version of the grpc extension? I remember seeing a few fixes related to this in the last few releases.
> 
> The latest version on [PECL](https://pecl.php.net/package-changelog.php?package=gRPC) is 1.70.0, but it's unclear if [v1.70.1](https://github.com/grpc/grpc/releases/tag/v1.70.1) addresses this.
> 
> I am using grpc 1.70.0, and still get similar error:`Uncaught Error: Maximum call stack size of 10436608 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?`
> 
> PHP Version 8.3.10

Version of grpc 1.71.0 with php 8.4.4, same error:
> Maximum call stack size of 10436608 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?

I will need to set `zend.max_allowed_stack_size=-1` just for this issue

**Comment by NiceRath** [comment]
We also still see this issue on `php8.3.19` and `1.71.0`

**Comment by yusufcemalcelebi** [comment]
I also receive this with php version `8.3.17` and grpc extension version `1.71.0`. My errors were related with google packages and now i'm enforcing them to use Rest instead of gRPC to resolve this issue. It's not the best way considering gRPC is more performant.

**Comment by stephanlueckl** [comment]
Bug is still here with PHP Version 8.3.23 and grpc extension version 1.72.0

**Comment by BSN4** [comment]
For anyone still hitting this segfault — [grpc-php-rs](https://github.com/BSN4/grpc-php-rs) is a drop-in replacement for ext-grpc that doesn't use the C gRPC core, abseil, or any C dependencies. No segfaults from grpc_absl_log.

```sh
pie install bsn4/grpc
```

Or in Docker:
```dockerfile
COPY --from=ghcr.io/bsn4/grpc-php-rs:latest-php8.3 /usr/local/ /usr/local/
```

**Comment by pawbhard** [comment]
Error "[Error: ](error: Maximum call stack size of 8339456 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?)" has been fixed in grpc 1.80 release branch.

Please tryout with latest

**Comment by pawbhard** [comment]
@bshaffer This bug description mention about 
"[Error: ](error: Maximum call stack size of 8339456 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?)" which is fixed.

Please see if duplicate bug https://github.com/googleapis/gax-php/issues/581 is also related to this, as that has some other backtrace (hope I am reading it right) if needed raise a new issue for that on gRPC

**Comment by bshaffer** [comment]
https://github.com/googleapis/gax-php/issues/581 looks to be a fundamentally different issue than the "Maximum call stack size" error. I though this was the same issue, since the title says it's a segfault, but maybe not.

I've reopened the GAX one and I'll submit a bug here with the information there instead.

**Comment by bshaffer** [comment]
OK I've submitted a new bug to gRPC which contains the separate error: https://github.com/grpc/grpc/issues/42044
