### ISSUE TITLE
All cloud_to_prod and cloud_to_prod_auth tests seem to be failing.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4831]
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/1497/consoleFull

**Comment by jtattermusch** [comment]
This seems to be the main reason of interop test runs piling up, as  when some interop tests are flaky or timeout, they are retried. Here almost all the cloud to prod tests are failing, so with retries, the entire suite takes much longer to run.

**Comment by jtattermusch** [comment]
@adelez , have you run the cloud_to_prod interop tests on your localhost yesterday? What results did you obtain?  I am reasonably sure the route cause can be found by running the interop tests locally (potentially stepping through the code) and seeing what goes wrong.

**Comment by jtattermusch** [comment]
(I don't have a linux machine at hand at this moment).

**Comment by jtattermusch** [comment]
I tried running C# cloud_to_prod tests locally (without using docker and I am getting error `Status(StatusCode=Internal, Detail="Received RST_STREAM err=2")`

**Comment by jtattermusch** [comment]
@yang-g any ideas?

**Comment by yang-g** [comment]
I think the service address change may be in some intermediate stage. I
tried all three names last night with a local built client but none seem to
work. If this is causing load on the jenkins, I think we can disable the
tests.

**Comment by jtattermusch** [comment]
I can confirm I tried grpc-test.sandbox.google.com and grpc-test.sandbox.googleapis.com and none of them works.

**Comment by jtattermusch** [comment]
Alright, to speed up processing of interop tests, I'm just removed the --allow_flakes flag in gRPC_interop_pull_requests jenkins job. That might result in some flakes on PRs, but it's definitely a much better option than having a huge build queue and tests not running.

**Comment by adelez** [comment]
I just managed to run the test manually with #4790 before I had to run and
all tests failed. I'll look at the results now.
Plus we have issue building docker on one grpc-interop2.
I added 'interop' label to grpc-canary-interop1. It can at least run the
tests but of course they are all failing.

**Comment by jtattermusch** [comment]
Btw, list of failing tests is here: https://grpc-testing.appspot.com/job/gRPC_interop_master/2526/#showFailuresLink

**Comment by yang-g** [comment]
This should be fixed now.

**Comment by yang-g** [comment]
I meant when #4790 is checked in.

**Comment by yang-g** [comment]
I think we can close this once we see some green on jenkins.

**Comment by jtattermusch** [comment]
It looks like cloud_to_prod tests started passing, but cloud to prod auth tests are still failing.

https://grpc-testing.appspot.com/job/gRPC_interop_master/2531/#showFailuresLink

**Comment by yang-g** [comment]
All the failed tests are auth tests, but some auth tests are passing
(compute_engine_creds are all passing).
C++ test has error message complaining about invalid json. Maybe we messed
up the json key file somehow.

**Comment by adelez** [comment]
Do we need to update some cred/key file now that the url is changed?

**Comment by adelez** [comment]
I tested with the correct key file locally and still got the same error.

**Comment by adelez** [comment]
Yang is already debugging this issue.

**Comment by yang-g** [comment]
I uploaded the key file again and the auth tests should pass now. Still waiting to confirm.

**Comment by yang-g** [comment]
They seem to pass from: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/1553/consoleFull
