### ISSUE TITLE
Ruby client hangs when connecting to cloud datastore with the Puma webserver

### ISSUE THREAD

**Issue by bmclean** [grpc/grpc#6577]
After updating gcloud-ruby (to v0.9.0) to use cloud datastore v1beta3  the ruby client hangs when connecting to the datastore. We are using gcloud-ruby in a Rails app and can reproduce the hang with both the Puma and Phusion Passenger web servers on Heroku. However, WEBrick seems to work fine on Heroku.

We added the environment variable `GRPC_TRACE=all` to capture this [trace](https://gist.github.com/bmclean/fedc6a5589ce714bd744694ed2ea7e54) using Puma.

The datastore dataset is initialized like this:
`dataset = Gcloud.datastore name_of_project`
and we experience the hang after the first call like this:
`dataset.run query`

It appears that grpc connects to the server, completes a TLS handshake, and starts initializing an HTTP2 stream. And then it suddenly stops, and ~20 seconds later, Heroku kills it.

**Comment by murgatroid99** [comment]
My initial guess from seeing the trace is that Puma and Phusion Passenger may do something to outgoing requests that prevents HTTP2 streams from working. I'll have to investigate more to verify that, though.

**Comment by bmclean** [comment]
This [Rails app](https://github.com/Agrimatics/active-model-cloud-datastore) that can be used to recreate the problem. It can be run locally connected to an actual datastore to see the problem. To run it locally in development mode comment out the `ENV['DATASTORE_EMULATOR_HOST'] ` line and add the desired cloud datastore project in config/initializers/cloud_datastore.rb:

Example:
```
module CloudDatastore
  if Rails.env.development?
    # ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8180'
  elsif Rails.env.test?
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8181'
  else
    ENV['GCLOUD_KEYFILE_JSON'] = '{"private_key": "' + ENV['SERVICE_ACCOUNT_PRIVATE_KEY'] + '",
      "client_email": "' + ENV['SERVICE_ACCOUNT_CLIENT_EMAIL'] + '"}'
  end

  def self.dataset
    config = Rails.application.config.database_configuration[Rails.env]['dataset_id']
    @dataset ||= Gcloud.datastore('datastore-project-name-here')
  end

  def self.reset_dataset
    @dataset = nil
  end
end
```

I worked through the code and got to here:

It starts with a dataset.run(query).

The method 'run' in Gcloud::Datastore::Dataset calls service.run_query.

The method 'run_query' in Gcloud::Datastore::Service calls datastore.run_query.

The method 'run_query' is created with a define_method in GRPC::GenericService::Dsl.rpc_stub_class.

The defined method run_query calls GRPC::ClientStub.request_response, which builds a new_active_call object and calls request_response on it. That method then calls GRPC:ActiveCall.start_call which in turn calls ActiveCall.client_invoke which has a call.run_batch method which fails to return anything and hangs.

The ActiveCall.client_invoke does have the following comment:
Flow Control note: this blocks until flow control accepts that client request can go ahead.

**Comment by murgatroid99** [comment]
To be clear, are you saying that this problem reproduces locally using the datastore emulator, or only using an actual datastore?

**Comment by bmclean** [comment]
@murgatroid99 Only when connecting to an actual datastore.

**Comment by bmclean** [comment]
The demo Rails app is configured to use Puma (which hangs). If you comment out the puma line from the Gemfile and delete (or rename) the Procfile then starting the server with `rails s` will use WEBrick  (which seems to work).

**Comment by obieq** [comment]
Don't know if this helps or not... My project has this issue when running Heroku/Puma.  However, Heroku/Thin works.

**Comment by bmclean** [comment]
As the problem seems to occur with web servers that fork multiple processes, I tried disabling Puma's clustered mode (which forks processes) by configuring `workers 0`. This did allow a localhost Rails app connected to an actual datastore to function properly. As I was creating the Gcloud.datastore dataset object in a Rails initializer, I moved it elsewhere which then allowed a localhost Rails app with multiple Puma processes connected to an actual datastore to function properly.

However, this still did not work when deployed to Heroku and running in production mode. One difference between development and production environments is that eager loading is enabled at boot for production environments. I set `config.eager_load = false` in the config/environments/production.rb and deployed to Heroku which does work.

Any idea why the Gcloud.datastore dataset object can't be instantiated in a Rails initializer when using multiple processes or with eager_load enabled?

**Comment by murgatroid99** [comment]
OK, that makes sense, and I think we've actually run into this problem before (but I didn't recognize it). I'm not exactly sure why, but the way that the gRPC library initializes does not persist properly across forks. If you load it eagerly, you load it and then fork, so the subprocesses don't have correct initialization. But if you fork and then load it in each worker, everything initializes correctly.

**Comment by blowmage** [comment]
@bmclean Try setting the datastore object in `Thread.current` instead of an instance variable.

**Comment by blowmage** [comment]
```ruby
module CloudDatastore
  if Rails.env.development?
    # ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8180'
  elsif Rails.env.test?
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8181'
  else
    ENV['GCLOUD_KEYFILE_JSON'] = '{"private_key": "' + ENV['SERVICE_ACCOUNT_PRIVATE_KEY'] + '",
      "client_email": "' + ENV['SERVICE_ACCOUNT_CLIENT_EMAIL'] + '"}'
  end

  def self.dataset
    config = Rails.application.config.database_configuration[Rails.env]['dataset_id']
    Thread.current[:dataset] ||= Gcloud.datastore('datastore-project-name-here')
  end

  def self.reset_dataset
    Thread.current[:dataset] = nil
  end
end
```

**Comment by bmclean** [comment]
@blowmage I tried `Thread.current` but it doesn't  help in this scenario.

The trick that does work is to make sure the gRPC library is initialized after the process forks. So for example, my CloudDatastore module is in a Rails initializer and the previous version looked like this:
```
require 'gcloud/datastore'

module CloudDatastore
  if Rails.env.development?
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8180'
  elsif Rails.env.test?
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8181'
  else
    ENV['GCLOUD_KEYFILE_JSON'] = '{"private_key": "' + ENV['SERVICE_ACCOUNT_PRIVATE_KEY'] + '",
      "client_email": "' + ENV['SERVICE_ACCOUNT_CLIENT_EMAIL'] + '"}'
  end

  def self.dataset
    config = Rails.application.config.database_configuration[Rails.env]['dataset_id']
    @dataset ||= Gcloud.datastore(config)
  end

  def self.reset_dataset
    @dataset = nil
  end
end
``` 
I changed it so that `require 'gcloud/datastore' ` is inside the dataset method like this:
```
module CloudDatastore
  if Rails.env.development?
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8180'
  elsif Rails.env.test?
    ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8181'
  else
    ENV['GCLOUD_KEYFILE_JSON'] = '{"private_key": "' + ENV['SERVICE_ACCOUNT_PRIVATE_KEY'] + '",
      "client_email": "' + ENV['SERVICE_ACCOUNT_CLIENT_EMAIL'] + '"}'
  end

  def self.dataset
    require 'gcloud/datastore'
    config = Rails.application.config.database_configuration[Rails.env]['dataset_id']
    @dataset ||= Gcloud.datastore(config)
  end

  def self.reset_dataset
    @dataset = nil
  end
end
```
With some puts debugging added to the GRPC::GenericService::Dsl rpc `name` variable Puma now starts like this:
```
[99383] Puma starting in cluster mode...
[99383] * Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
[99383] * Min threads: 5, max threads: 5
[99383] * Environment: production
[99383] * Process workers: 2
[99383] * Preloading application
[99383] * Listening on tcp://localhost:3000
[99383] Use Ctrl-C to stop
Puma Worker 99407 booted at 2016-05-19 09:27:55 -0600
Puma Worker 99408 booted at 2016-05-19 09:27:55 -0600
*****************************
Lookup
*****************************
RunQuery
*****************************
BeginTransaction
*****************************
Commit
*****************************
Rollback
*****************************
Lookup
*****************************
AllocateIds
*****************************
RunQuery
*****************************
BeginTransaction
*****************************
Commit
*****************************
Rollback
*****************************
AllocateIds
```

**Comment by blowmage** [comment]
Okay, so the problem is loading GRPC before forking, not instantiating a GRPC object before forking?

Sounds like this is fixed in newer releases. Can't wait to move to it. (Currently blocked by grpc/grpc#6571)

**Comment by murgatroid99** [comment]
That problem with loading grpc before forking is not fixed in the newer release, and I do not expect it to be fixed any time soon.

**Comment by blowmage** [comment]
Gotcha. Thanks for the clarification!

**Comment by bmclean** [comment]
@murgatroid99 Do you want this issue left open?

**Comment by murgatroid99** [comment]
I think it's worth leaving open, as long as that problem still exists.

**Comment by jrun** [comment]
#8798

**Comment by muxi** [comment]
ping

**Comment by apolcyn** [comment]
closing as dupe of https://github.com/grpc/grpc/issues/7951
