### ISSUE TITLE
NodeJS cluster module

### ISSUE THREAD

**Issue by marshauf** [grpc/grpc#6976]
Hello,

is it possible to use the NodeJS cluster module with grpc?

**Comment by murgatroid99** [comment]
Currently, gRPC does not work with cluster. We are working on changes to add at least partial support.

**Comment by ychen11** [comment]
@murgatroid99 How is this issue going? We met the same problem, single process on node is like a hell

**Comment by murgatroid99** [comment]
I'm working on it, but it has required some major internal changes. Pull request #8125 is a large part of it, and I expect to have this done by the end of the quarter.

**Comment by danamajid** [comment]
+1

**Comment by ychen11** [comment]
@murgatroid99 How is this issue now? It's been already 2017 Q1.
I saw that PR #8125 was merged?

**Comment by murgatroid99** [comment]
The next step is getting grpc/proposal#8 accepted and implemented.

**Comment by leonlau** [comment]
+1

**Comment by asinha08** [comment]
Is this issue fixed

**Comment by funwun** [comment]
fixed?

**Comment by ddibiase** [comment]
Would love to see this supported as well. Hopefully there's a fix soon!

**Comment by omidnavi** [comment]
Hi,
is this supported now ?

**Comment by nicolasnoble** [comment]
Still not. The fact that the core added SO_REUSEPORT support for Linux diminished the priority on this one.

**Comment by ychen11** [comment]
man, it's been 2 years........we actually refactored our code in GO already. 
I will see when this will be fixed, maybe the day deno takes place of node.

**Comment by omidnavy** [comment]
Kubernetes is in charge for doing this, clustering and etc. you shoudlnt use nodejs cluster module or something like pm2 .

**Comment by nicolasnoble** [comment]
The main reason is that grpc should by default allow opening the same TCP socket multiple times from different processes, effectively doing the same thing, in a simpler manner.

**Comment by omidnavy** [comment]
@pratapdd there is no need of fixing this while (as you also mentioned) clustering job should handle by other tools like kubernetes.

**Comment by yunnysunny** [comment]
Our team not use kubernetes yet, we have to create multiple hosts. It's annoying.
